services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql-files/

volumes:
  mongo-data:
  mysql-data:
## docker volume
# mkdir databaseStorage && cd databaseStorage && docker volume create mongo-data && docker volume create mysql-data

## python virtual envrionment
# python -m venv venv

## install requirements
# Windows: .\venv\Scripts\pip.exe install -r requirements.txt && .\venv\Scripts\pip install cryptography
# Linux/Unix/MacOs: ./venv/bin/pip install -r requirements.txt && ./venv/bin/pip install cryptography

## run app
# venv\Scripts\python.exe app.py